server:
  port: 8086

  datasource:
    url: jdbc:postgresql://localhost:5432/it_mentor_community_platform?currentSchema=job-market-analytics-service
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092