### 201-Succefuly created / 409-Query already exists
POST http://localhost:8086/api/job-market-analytics/search-query
Content-Type: application/json
X-Telegram-User-id: 5
X-User-Roles: ADMIN

{
  "title": "Java Developer",
  "query": "NAME:(!\"Java\") NOT QA NOT AQA",
  "isEnabled": true
}


### 400-Validation failed (Title is required)
POST http://localhost:8086/api/job-market-analytics/search-query
Content-Type: application/json
X-Telegram-User-id: 5
X-User-Roles: ADMIN

{
  "query": "NAME:(!\"Java\") NOT QA NOT AQA",
  "isEnabled": true
}


### 400-Validation failed (Query is required)
POST http://localhost:8086/api/job-market-analytics/search-query
Content-Type: application/json
X-Telegram-User-id: 5
X-User-Roles: ADMIN

{
  "title": "Java Developer",
  "isEnabled": true
}


### 400-Validation failed (IsEnabled is required)
POST http://localhost:8086/api/job-market-analytics/search-query
Content-Type: application/json
X-Telegram-User-id: 5
X-User-Roles: ADMIN

{
  "title": "Java Developer",
  "query": "NAME:(!\"Java\") NOT QA NOT AQA",
  "isEnabled": null
}


### 400-Validation failed (IsEnabled is required)
POST http://localhost:8086/api/job-market-analytics/search-query
Content-Type: application/json
X-Telegram-User-id: 5
X-User-Roles: ADMIN

{
  "title": "Java Developer",
  "query": "NAME:(!\"Java\") NOT QA NOT AQA"
}


### 403-Access denied (missing X-Telegram-User-id)
POST http://localhost:8086/api/job-market-analytics/search-query
Content-Type: application/json
X-User-Roles: ADMIN

{
  "title": "Java Developer",
  "query": "NAME:(!\"Java\") NOT QA NOT AQA",
  "isEnabled": true
}


### 403-Access denied (missing X-User-Roles)
POST http://localhost:8086/api/job-market-analytics/search-query
Content-Type: application/json
X-Telegram-User-id: 5

{
  "title": "Java Developer",
  "query": "NAME:(!\"Java\") NOT QA NOT AQA",
  "isEnabled": true
}


### 403-Access denied (wrong X-User-Roles)
POST http://localhost:8086/api/job-market-analytics/search-query
Content-Type: application/json
X-Telegram-User-id: 5
X-User-Roles: STUDENT

{
  "title": "Java Developer",
  "query": "NAME:(!\"Java\") NOT QA NOT AQA",
  "isEnabled": true
}